---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "home-assistant-integrations.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "home-assistant-integrations.selectors" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "home-assistant-integrations.selectors" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: home-assistant-integrations
        {{- $repo := .Values.image.repository }}
        {{- $tag := .Values.image.tag | default .Chart.AppVersion }}
        image: {{ printf "%s:%s" $repo $tag }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        ports:
        - containerPort: 8080
          name: api
        readinessProbe:
          httpGet:
            path: /readyz
            port: api
          initialDelaySeconds: 5
